import type { AnalysisResult } from '@/types/github';

function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
}

function formatSize(kb: number) {
  if (kb < 1024) return `${kb} KB`;
  return `${(kb / 1024).toFixed(1)} MB`;
}

function calcLangPercents(languages: Record<string, number>) {
  const total = Object.values(languages).reduce((a, b) => a + b, 0);
  return Object.entries(languages)
    .map(([name, bytes]) => ({ name, pct: ((bytes / total) * 100).toFixed(1) }))
    .sort((a, b) => parseFloat(b.pct) - parseFloat(a.pct))
    .slice(0, 8);
}

// ─── Markdown Export ────────────────────────────────────────────────────────

export function generateMarkdown(result: AnalysisResult): string {
  const { repo, languages, importantFiles, improvements, projectType, techStack } = result;
  const langs = calcLangPercents(languages);
  const totalFiles = result.tree.filter(t => t.type === 'blob').length;

  const priorityOrder = { high: 0, medium: 1, low: 2 };
  const sortedImprovements = [...improvements].sort(
    (a, b) => priorityOrder[a.priority] - priorityOrder[b.priority]
  );

  const lines: string[] = [
    `# RepoLens Analysis Report`,
    ``,
    `> Generated by **[RepoLens](https://repolens.app)** on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
    ``,
    `---`,
    ``,
    `## Repository Overview`,
    ``,
    `| Field | Value |`,
    `|-------|-------|`,
    `| **Name** | [${repo.full_name}](${repo.html_url}) |`,
    `| **Project Type** | ${projectType} |`,
    `| **Description** | ${repo.description || '_No description provided_'} |`,
    `| **Visibility** | ${repo.visibility} |`,
    `| **Default Branch** | \`${repo.default_branch}\` |`,
    `| **License** | ${repo.license?.name || '_None_'} |`,
    `| **Repository Size** | ${formatSize(repo.size)} |`,
    `| **Total Files** | ${totalFiles.toLocaleString()} |`,
    `| **Created** | ${formatDate(repo.created_at)} |`,
    `| **Last Updated** | ${formatDate(repo.updated_at)} |`,
    `| **Last Push** | ${formatDate(repo.pushed_at)} |`,
    ``,
    `### Stats`,
    ``,
    `| ⭐ Stars | 🍴 Forks | 👁️ Watchers | 🐛 Open Issues |`,
    `|---------|---------|------------|--------------|`,
    `| ${repo.stargazers_count.toLocaleString()} | ${repo.forks_count.toLocaleString()} | ${repo.watchers_count.toLocaleString()} | ${repo.open_issues_count.toLocaleString()} |`,
    ``,
  ];

  if (repo.topics && repo.topics.length > 0) {
    lines.push(`### Topics`, ``);
    lines.push(repo.topics.map(t => `\`${t}\``).join(' ') + ``, ``);
  }

  if (techStack.length > 0) {
    lines.push(`### Tech Stack`, ``);
    lines.push(techStack.map(t => `\`${t}\``).join(' · ') + ``, ``);
  }

  lines.push(
    `---`,
    ``,
    `## Programming Languages`,
    ``,
    `| Language | Percentage |`,
    `|----------|-----------|`,
    ...langs.map(l => `| ${l.name} | ${l.pct}% |`),
    ``
  );

  if (importantFiles.length > 0) {
    lines.push(
      `---`,
      ``,
      `## Important Files`,
      ``,
      `| File | Description |`,
      `|------|-------------|`,
      ...importantFiles.map(f => `| \`${f.path}\` | ${f.reason} |`),
      ``
    );
  }

  if (sortedImprovements.length > 0) {
    lines.push(
      `---`,
      ``,
      `## Suggested Improvements`,
      ``,
      `_${sortedImprovements.length} recommendation${sortedImprovements.length !== 1 ? 's' : ''} found_`,
      ``
    );

    const byPriority = {
      high: sortedImprovements.filter(i => i.priority === 'high'),
      medium: sortedImprovements.filter(i => i.priority === 'medium'),
      low: sortedImprovements.filter(i => i.priority === 'low'),
    };

    const labels: Record<string, string> = { high: '🔴 High Priority', medium: '🟡 Medium Priority', low: '🟢 Low Priority' };

    for (const [level, items] of Object.entries(byPriority)) {
      if (items.length === 0) continue;
      lines.push(`### ${labels[level]}`, ``);
      for (const imp of items) {
        lines.push(`#### ${imp.title}`, ``, `> **Category:** ${imp.category}`, ``, imp.description, ``);
      }
    }
  } else {
    lines.push(`---`, ``, `## Improvements`, ``, `🎉 No major improvements detected — repository is in great shape!`, ``);
  }

  lines.push(`---`, ``, `_Report generated by RepoLens · ${new Date().toISOString()}_`);

  return lines.join('\n');
}

export function downloadMarkdown(result: AnalysisResult) {
  const md = generateMarkdown(result);
  const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `repolens-${result.repo.full_name.replace('/', '-')}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
  console.log('[RepoLens] Markdown report downloaded');
}

// ─── PDF Export ──────────────────────────────────────────────────────────────

export async function downloadPDF(result: AnalysisResult) {
  const { jsPDF } = await import('jspdf');

  const { repo, languages, importantFiles, improvements, projectType, techStack } = result;
  const langs = calcLangPercents(languages);
  const totalFiles = result.tree.filter(t => t.type === 'blob').length;
  const sortedImprovements = [...improvements].sort(
    (a, b) => ({ high: 0, medium: 1, low: 2 }[a.priority] - { high: 0, medium: 1, low: 2 }[b.priority])
  );

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const W = 210;
  const H = 297;
  const ML = 16;   // margin left
  const MR = 16;   // margin right
  const CW = W - ML - MR; // content width
  let y = 0;

  // ── color helpers
  const COL = {
    bg: [10, 14, 20] as [number, number, number],
    card: [18, 24, 34] as [number, number, number],
    border: [36, 46, 60] as [number, number, number],
    green: [52, 211, 100] as [number, number, number],
    cyan: [34, 211, 238] as [number, number, number],
    muted: [120, 140, 165] as [number, number, number],
    fg: [220, 230, 245] as [number, number, number],
    white: [255, 255, 255] as [number, number, number],
    red: [239, 68, 68] as [number, number, number],
    yellow: [234, 179, 8] as [number, number, number],
    lowGreen: [34, 197, 94] as [number, number, number],
    accent: [99, 102, 241] as [number, number, number],
  };

  function setFill(c: [number, number, number]) { doc.setFillColor(...c); }
  function setDraw(c: [number, number, number]) { doc.setDrawColor(...c); }
  function setTextColor(c: [number, number, number]) { doc.setTextColor(...c); }

  // page background
  function fillPage() {
    setFill(COL.bg);
    doc.rect(0, 0, W, H, 'F');
  }

  // check page overflow
  function checkPage(needed = 10) {
    if (y + needed > H - 12) {
      doc.addPage();
      fillPage();
      y = 14;
    }
  }

  function sectionTitle(text: string, icon = '') {
    checkPage(14);
    y += 4;
    setFill(COL.card);
    setDraw(COL.border);
    doc.roundedRect(ML, y, CW, 9, 1.5, 1.5, 'FD');
    setTextColor(COL.green);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.text(`${icon ? icon + ' ' : ''}${text}`, ML + 4, y + 6);
    y += 13;
  }

  function row(label: string, value: string, indent = 0) {
    checkPage(7);
    const labelW = 44;
    setTextColor(COL.muted);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(label, ML + indent, y);
    setTextColor(COL.fg);
    doc.setFont('helvetica', 'bold');
    // wrap value
    const lines = doc.splitTextToSize(value, CW - labelW - indent - 2);
    doc.text(lines, ML + labelW + indent, y);
    y += Math.max(5.5, lines.length * 4.5);
  }

  function divider() {
    checkPage(4);
    setDraw(COL.border);
    doc.setLineWidth(0.2);
    doc.line(ML, y, ML + CW, y);
    y += 5;
  }

  // ── PAGE 1: Header ─────────────────────────────────────────────────────────
  fillPage();

  // Hero banner
  setFill(COL.card);
  doc.rect(0, 0, W, 38, 'F');

  // green accent bar
  setFill(COL.green);
  doc.rect(0, 36, W, 2, 'F');

  // Logo mark
  setFill([25, 35, 50]);
  doc.roundedRect(ML, 8, 14, 14, 2, 2, 'F');
  setTextColor(COL.green);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('RL', ML + 3.5, 17.5);

  // Title
  setTextColor(COL.fg);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('RepoLens', ML + 18, 17);
  setTextColor(COL.muted);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('GitHub Repository Analysis Report', ML + 18, 23);

  // Date stamp top right
  setTextColor(COL.muted);
  doc.setFontSize(7.5);
  doc.text(`Generated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' })}`, W - MR - 42, 14);
  doc.text(`${repo.full_name}`, W - MR - 42, 20);

  y = 48;

  // ── Repo card ─────────────────────────────────────────────────────────────
  setFill(COL.card);
  setDraw(COL.border);
  doc.roundedRect(ML, y, CW, 10, 1.5, 1.5, 'FD');

  setTextColor(COL.green);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(repo.full_name, ML + 4, y + 7);

  setFill(COL.green);
  const tagText = projectType;
  const tagW = doc.getTextWidth(tagText) + 6;
  doc.roundedRect(W - MR - tagW - 2, y + 2.5, tagW, 5.5, 1, 1, 'F');
  setTextColor(COL.bg);
  doc.setFontSize(7);
  doc.setFont('helvetica', 'bold');
  doc.text(tagText, W - MR - tagW + 1, y + 6.7);

  y += 14;

  // description
  if (repo.description) {
    setTextColor(COL.muted);
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'normal');
    const descLines = doc.splitTextToSize(repo.description, CW);
    doc.text(descLines, ML, y);
    y += descLines.length * 4.5 + 3;
  }

  // ── Stats grid ────────────────────────────────────────────────────────────
  checkPage(24);
  const stats = [
    { label: 'Stars', value: repo.stargazers_count.toLocaleString(), col: COL.yellow },
    { label: 'Forks', value: repo.forks_count.toLocaleString(), col: COL.accent },
    { label: 'Watchers', value: repo.watchers_count.toLocaleString(), col: COL.cyan },
    { label: 'Open Issues', value: repo.open_issues_count.toLocaleString(), col: [251, 146, 60] as [number, number, number] },
  ];
  const boxW = (CW - 9) / 4;
  stats.forEach((s, i) => {
    const bx = ML + i * (boxW + 3);
    setFill(COL.card);
    setDraw(COL.border);
    doc.roundedRect(bx, y, boxW, 16, 1.5, 1.5, 'FD');
    setTextColor(s.col);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(s.value, bx + boxW / 2, y + 8.5, { align: 'center' });
    setTextColor(COL.muted);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.text(s.label, bx + boxW / 2, y + 13.5, { align: 'center' });
  });
  y += 21;

  // ── Meta info ─────────────────────────────────────────────────────────────
  divider();
  row('Visibility', repo.visibility);
  row('Branch', repo.default_branch);
  row('License', repo.license?.name || 'None');
  row('Size', formatSize(repo.size));
  row('Files', totalFiles.toLocaleString());
  row('Created', formatDate(repo.created_at));
  row('Last Updated', formatDate(repo.updated_at));

  // ── Tech Stack ────────────────────────────────────────────────────────────
  if (techStack.length > 0) {
    sectionTitle('Tech Stack', '⚙');
    let tx = ML;
    const tagY = y;
    techStack.forEach(tech => {
      const tw = doc.getTextWidth(tech) + 8;
      if (tx + tw > ML + CW) { y += 8; tx = ML; }
      checkPage(9);
      setFill(COL.card);
      setDraw(COL.border);
      doc.roundedRect(tx, y - 4, tw, 6, 1, 1, 'FD');
      setTextColor(COL.fg);
      doc.setFontSize(7.5);
      doc.setFont('helvetica', 'bold');
      doc.text(tech, tx + 4, y + 0.5);
      tx += tw + 3;
    });
    y += 8;
  }

  // ── Languages ─────────────────────────────────────────────────────────────
  sectionTitle('Programming Languages', '◈');

  // colored bar
  checkPage(10);
  const barH = 5;
  let bx = ML;
  const LANG_COLORS_HEX: Record<string, [number, number, number]> = {
    TypeScript: [49, 120, 198], JavaScript: [247, 223, 30], Python: [53, 114, 165],
    Java: [176, 114, 25], 'C#': [23, 134, 0], 'C++': [243, 75, 125],
    Go: [0, 173, 216], Rust: [222, 165, 132], Ruby: [112, 21, 22],
    PHP: [79, 93, 149], Swift: [250, 115, 67], Kotlin: [169, 123, 255],
    Shell: [137, 224, 81], HTML: [227, 76, 38], CSS: [86, 61, 124],
  };
  const palette: [number,number,number][] = [[99,102,241],[236,72,153],[245,158,11],[16,185,129],[59,130,246],[139,92,246],[239,68,68],[6,182,212]];

  langs.forEach((l, i) => {
    const c = LANG_COLORS_HEX[l.name] || palette[i % palette.length];
    const segW = (parseFloat(l.pct) / 100) * CW;
    setFill(c);
    doc.rect(bx, y, segW, barH, 'F');
    bx += segW;
  });
  y += barH + 4;

  // legend grid
  const cols2 = 2;
  const colW2 = CW / cols2;
  langs.forEach((l, i) => {
    checkPage(7);
    const col = i % cols2;
    const lx = ML + col * colW2;
    if (col === 0 && i > 0) y += 5.5;
    const c = LANG_COLORS_HEX[l.name] || palette[i % palette.length];
    setFill(c);
    doc.circle(lx + 2, y - 1, 1.5, 'F');
    setTextColor(COL.fg);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(l.name, lx + 6, y);
    setTextColor(COL.muted);
    doc.text(`${l.pct}%`, lx + colW2 - 10, y, { align: 'right' });
  });
  y += 8;

  // ── Important Files ────────────────────────────────────────────────────────
  if (importantFiles.length > 0) {
    sectionTitle('Important Files', '★');
    importantFiles.forEach(file => {
      checkPage(10);
      setFill(COL.card);
      setDraw(COL.border);
      doc.roundedRect(ML, y - 3, CW, 8.5, 1.2, 1.2, 'FD');
      setTextColor(COL.green);
      doc.setFontSize(8);
      doc.setFont('courier', 'bold');
      doc.text(file.path, ML + 4, y + 2.5);
      setTextColor(COL.muted);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      const reason = doc.splitTextToSize(file.reason, CW - 8);
      doc.text(reason, ML + 4, y + 6.5);
      y += 8.5 + 2;
    });
    y += 2;
  }

  // ── Improvements ──────────────────────────────────────────────────────────
  if (sortedImprovements.length > 0) {
    sectionTitle(`Suggested Improvements (${sortedImprovements.length})`, '✦');

    const prioColors: Record<string, [number, number, number]> = {
      high: COL.red, medium: COL.yellow, low: COL.lowGreen,
    };
    const prioLabels: Record<string, string> = { high: 'HIGH', medium: 'MED', low: 'LOW' };

    sortedImprovements.forEach(imp => {
      const descLines = doc.splitTextToSize(imp.description, CW - 12);
      const cardH = 6 + 5 + descLines.length * 4 + 5;
      checkPage(cardH + 4);

      setFill(COL.card);
      setDraw(COL.border);
      doc.roundedRect(ML, y, CW, cardH, 1.5, 1.5, 'FD');

      // priority dot
      const pc = prioColors[imp.priority];
      setFill(pc);
      doc.circle(ML + 4.5, y + 5.5, 2.5, 'F');

      // title
      setTextColor(COL.fg);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.text(imp.title, ML + 10, y + 7);

      // badges
      const catText = imp.category;
      const catW = doc.getTextWidth(catText) + 6;
      const prioText = prioLabels[imp.priority];
      const prioW = doc.getTextWidth(prioText) + 6;
      const badgeY = y + 2;
      const badgeRight = ML + CW - 2;

      setFill(pc);
      doc.roundedRect(badgeRight - prioW, badgeY, prioW, 4.5, 0.8, 0.8, 'F');
      setTextColor(COL.bg);
      doc.setFontSize(6.5);
      doc.setFont('helvetica', 'bold');
      doc.text(prioText, badgeRight - prioW / 2, badgeY + 3.2, { align: 'center' });

      setFill(COL.border);
      doc.roundedRect(badgeRight - prioW - catW - 3, badgeY, catW, 4.5, 0.8, 0.8, 'F');
      setTextColor(COL.muted);
      doc.setFontSize(6.5);
      doc.setFont('helvetica', 'normal');
      doc.text(catText, badgeRight - prioW - catW / 2 - 3, badgeY + 3.2, { align: 'center' });

      // description
      setTextColor(COL.muted);
      doc.setFontSize(7.8);
      doc.setFont('helvetica', 'normal');
      doc.text(descLines, ML + 10, y + 13);

      y += cardH + 3;
    });
  }

  // ── Footer on all pages ────────────────────────────────────────────────────
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    setFill(COL.card);
    doc.rect(0, H - 10, W, 10, 'F');
    setTextColor(COL.muted);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.text('RepoLens · github.com analyzer', ML, H - 3.5);
    doc.text(`Page ${i} of ${pageCount}`, W - MR, H - 3.5, { align: 'right' });
  }

  doc.save(`repolens-${repo.full_name.replace('/', '-')}.pdf`);
  console.log('[RepoLens] PDF report downloaded');
}
